apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.service.label}}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: {{.Values.service.portname}}
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
    protocol: TCP

  # Note here that we match both the app and the version
  selector:
    app: {{.Values.service.selector}} # change selector here to always switch between deployment types i.e blue or green